"""empty message

Revision ID: d352c6aec3a7
Revises: d9555edacf99
Create Date: 2019-10-11 22:49:08.986006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd352c6aec3a7'
down_revision = 'd9555edacf99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=64), nullable=True),
    sa.Column('file_path', sa.String(length=128), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_model_file_name'), 'image_model', ['file_name'], unique=True)
    op.create_index(op.f('ix_image_model_file_path'), 'image_model', ['file_path'], unique=True)
    op.create_index(op.f('ix_image_model_thumbnail_path'), 'image_model', ['thumbnail_path'], unique=True)
    op.drop_index('ix_image_file_name', table_name='image')
    op.drop_index('ix_image_file_path', table_name='image')
    op.drop_index('ix_image_thumbnail_path', table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=96), nullable=True),
    sa.Column('thumbnail_path', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_image_thumbnail_path', 'image', ['thumbnail_path'], unique=1)
    op.create_index('ix_image_file_path', 'image', ['file_path'], unique=1)
    op.create_index('ix_image_file_name', 'image', ['file_name'], unique=1)
    op.drop_index(op.f('ix_image_model_thumbnail_path'), table_name='image_model')
    op.drop_index(op.f('ix_image_model_file_path'), table_name='image_model')
    op.drop_index(op.f('ix_image_model_file_name'), table_name='image_model')
    op.drop_table('image_model')
    # ### end Alembic commands ###
