"""empty message

Revision ID: d9555edacf99
Revises: 4001fe2138ac
Create Date: 2019-10-03 21:39:30.867012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9555edacf99'
down_revision = '4001fe2138ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('thumbnail_path', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_image_thumbnail_path'), 'image', ['thumbnail_path'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_thumbnail_path'), table_name='image')
    op.drop_column('image', 'thumbnail_path')
    # ### end Alembic commands ###
